name: style_classifier_2
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.7
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=11.0.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.9.20
  - pytorch=2.5.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - albucore==0.0.21
      - albumentations==1.4.22
      - annotated-types==0.7.0
      - black==24.10.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.68.1
      - huggingface-hub==0.26.3
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markdown==3.7
      - matplotlib==3.9.2
      - mypy-extensions==1.0.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - protobuf==5.29.0
      - psutil==6.1.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pyparsing==3.2.0
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - regex==2024.11.6
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.19.0
      - setproctitle==1.3.4
      - simsimd==6.2.1
      - six==1.16.0
      - smmap==5.0.1
      - stringzilla==3.11.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wandb==0.18.7
      - werkzeug==3.1.3
      - zipp==3.21.0
